### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by FredyC** [NShahri/react-workbox#1]
Are you planning to add them? Would be a shame not to do it for such nice looking package.

**Comment by NShahri** [comment]
Thanks,

As I am not familiar with Typescript, it may takes time to do it.
it would be my high priority.

**Comment by NShahri** [comment]
@FredyC 
It is done in v0.4.0
Please let me know if there is any issue

**Comment by FredyC** [comment]
Whoa, that was fast :) Looks good to me, thanks!
